config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'products#index'


  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  resources :carts
  resources :products
  resources :orders
  
  devise_for :admins
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  get 'users', to: 'users#index', as: 'users' # --------- make only visible to admin
  get 'users/:id', to: 'users#show', as: 'user'
  

  namespace :admin do
    root to: 'products#index'
    resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  get 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'find_product_to_add_from_cart'
  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  get 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'find_product_to_delete_from_cart'
  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light px-5">
  <a class="navbar-brand" href="#">Project Mars</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= active_class(products_path) %>">
            <%= link_to 'Home', products_path, class: 'nav-link' %>
        </li>
        </ul>
        <ul class="navbar-nav">
            <% if user_signed_in? %>
                <li class="nav-item <%= active_class(edit_user_registration_path) %>">
                    <%= link_to "Hi, #{current_user.email}", edit_user_registration_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
                </li>
                <li class="nav-item<%= active_class(products_path) %>">
                    <%= link_to 'Product Catalog', products_path, class: 'nav-link'%>
                </li>
                <li class="nav-item<%= active_class(carts_path) %>">
                    <%= link_to 'My Cart', carts_path, class: 'nav-link'%>
                </li>
                <li class="nav-item<%= active_class(orders_path) %>">
                    <%= link_to 'All Orders', orders_path, class: 'nav-link'%>
                </li>    
            <% else %>
                <li class="nav-item <%= active_class(new_user_session_path) %>">
                    <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
                </li>
                <li class="nav-item <%= active_class(new_user_registration_path) %>">
                    <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
                </li>
            <% end %>
        </ul>
        <ul class="navbar-nav">
            <% if admin_signed_in? %>
                <li class="nav-item">
                    <%= button_to 'Admin Sign Out', destroy_admin_session_path, method: :delete, class: 'nav-link' %>
                </li>
            <% else %>
                <li class="nav-item <%= active_class(new_admin_session_path) %>">
                    <%= link_to 'Admin Sign In', new_admin_session_path, class: 'nav-link' %>
                </li>

            <% end %>
        </ul>
    </div>
</nav>

app/views/shared/_product.html.erb
<div class="card">
  <div class="card-body">
    <div class="card-title">
      <p>
        <%= product.name %>
      </p>
    </div>
    <div class="card-text">
      <p>
        <small> <%= product.description %></small>
      </p>
    </div>
    <div class="card-footer">
      <%= link_to "View", product_path(product), class: 'btn btn-primary' %>

    </div>
  </div>
</div>