config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'products#index'


  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  resources :carts
  resources :products
  resources :orders
  
  devise_for :admins
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  get 'users', to: 'users#index', as: 'users' # --------- make only visible to admin
  get 'users/:id', to: 'users#show', as: 'user'
  

  namespace :admin do
    root to: 'products#index'
    resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  get 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'find_product_to_add_from_cart'
  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  get 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'find_product_to_delete_from_cart'
  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :bigint           not null, primary key
#  email      :string
#  name       :string
#  status     :string           default("Pending")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Order < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :products, through: :line_item
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

    devise_group :order_checker, contains: [:user, :admin]
    before_action :authenticate_order_checker!

    def index
        @orders = Order.all
      end
    
      def show
        @order = Order.find(params[:id])
      end
    
      def new
        @order = Order.new
      end

      def create
        @order = Order.new(order_params)
        @current_cart.line_items.each do |item|
          @order.line_items << item
          item.cart_id = nil
        end
        @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        redirect_to orders_path
      end

      def update
        @order = Order.find(params[:id])
        if @order.update(params.require(:order).permit(:status))
          flash[:success] = "Order successfully updated!"
          redirect_to order_url(@order)
        else
          flash.now[:error] = "Order update failed"
          render :back
        end
      end
    
      
      private
        def order_params
          params.require(:order).permit(:name, :email)
        end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<h2>All Orders</h2>
<% @orders.each do |order| %>
<h2>Order <%= order.id %> </h2>
  <p>Name: <%= order.name %></p>
  <p>Email: <%= order.email %></p>
  <p>Order Status: <% if admin_signed_in? %>
    <%= bootstrap_form_with model: @order, url: order_path(@order), method: :patch, local: true do |f| %>
      <%= f.select :status, [['Approved'], ['Denied'], ['In progress']] %>
      <%= f.submit %>
    <% end %>
  <% else %>
    <%= order.status %>
  <% end %>  
  </p>
  <p><%= link_to 'View Order', order_path(order) %></p>
  <p>Items:
   <table class="table table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Product</th>
        <th>Quantity</th>
      </tr>
    </thead>
    <tbody>
      <% render(order.line_items)%>
    </tbody>
    </table>
  </p>   
<% end %>

app/views/orders/new.html.erb
<%= form_for(@order) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true, autofocus: true %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/orders/show.html.erb
<% if admin_signed_in? %>
  <%= bootstrap_form_with model: @order, url: order_path(@order), method: :patch, local: true do |f| %>
    <%= f.select :status, [['Approved'], ['Denied']] %>
    <%= f.submit %>
  <% end %>
<% end %>

<p> Order Number: <%= @order.id%></p>
<p>Name: <%= @order.name %></p>
<p>Email: <%= @order.email %></p>
<p>Order Status: </p>
<table class="table table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Product</th>
        <th>Quantity</th>
      </tr>
    </thead>

    <tbody>
        <%= render(@order.line_items) %>
    </tbody>
</table>