config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'products#index'


  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  resources :carts
  resources :products
  resources :orders
  
  devise_for :admins
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  get 'users', to: 'users#index', as: 'users' # --------- make only visible to admin
  get 'users/:id', to: 'users#show', as: 'user'
  

  namespace :admin do
    root to: 'products#index'
    resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  get 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'find_product_to_add_from_cart'
  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  get 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'find_product_to_delete_from_cart'
  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :bigint           not null, primary key
#  description :text             not null
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Product < ApplicationRecord
    validates :name, :description, presence: true

    before_destroy :not_referenced_by_any_line_item
    
    private
      
    def not_referenced_by_any_line_item
        unless line_items.empty?
            errors.add(:base, 'Line items present')
            throw :abort
        end
    end
end

app/controllers/Admin/products_controller.rb
class Admin::ProductsController < ApplicationController
    
    before_action :authenticate_admin!

    def index
        @products = Product.all
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.new(params.require(:product).permit(:name, :description))
        if @product.save
            #@category_array = params.dig(:product, :category_ids)
            #@category_array.each do |cat|
                #@category = Category.find(cat)
                #@product.categories << @category
            #end
            flash[:notice] = "Product added!"
            redirect_to admin_products_path
        else
            flash[:notice] = "Product can't be blank!"
            render 'admin/products/new'
        end
    end

    def edit
        @product = Product.find(params[:id])
    end

    def update
        @product = Product.find(params[:id])
        if @product.update(product_params)
            #@product.product_categories.destroy_all
            #@category_array = params.dig(:product, :category_ids)
            #@category_array.each do |cat|
                #@category = Category.find(cat)
                #@product.categories << @category
            #end
            flash[:notice] = "Product updated!"
            redirect_to admin_products_path
        else
            render :edit
        end
    end

    def destroy
        Product.destroy(params[:id])
        flash[:notice] = "Product removed!"
        redirect_to admin_products_path
    end

    private

        def product_params
            params.require(:product).permit(:name, :description, :price)
        end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def show
        @product = Product.find(params[:id])
    end

    def index
        @products = Product.all
        render :index
    end

    def new
        @product = Product.new
        render :new
    end

    def create
        @product = Product.new(params.require(:product).permit(:name, :description))
        if @product.save
          flash[:success] = "New product successfully added!"
          redirect_to products_url
        else
          flash.now[:error] = "Product creation failed"
          render :new
        end
    end

    def edit
        @product = Product.find(params[:id])
        render :edit
    end

    def update
        @product = Product.find(params[:id])
        if @product.update(params.require(:product).permit(:name, :description))
          flash[:success] = "Product successfully updated."
          redirect_to product_url(@product)
        else
          flash.now[:error] = "Product update failed."
          render :edit
        end
    end

    def destroy
        @product = Product.find(params[:id])
        @product.destroy
        flash[:success] = "The product was successfully destroyed."
        redirect_to products_url
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_admin_product.html.erb
<tr>
  <td><%=  admin_product.name  %></td>
  <td><%=  admin_product.description  %></td>
  <td><%= link_to 'Edit', edit_admin_product_path(admin_product) %></td>
  <td><%= button_to 'Delete', admin_product_path(admin_product), method: :delete %></td>
</tr>

app/views/admin/products/edit.html.erb
<h1 class="jumbotron">Edit a Product</h1>

<div class="container">

    <%= bootstrap_form_for [:admin, @product], class: "form-horizontal" do |f| %>

        <%= f.text_field :name %>
        <%= f.text_area :description %>
        <!-- <%#= f.association :categories, collection: Category.all, as: :check_boxes, include_hidden: false %> -->

        <%= f.button :submit %>
    
    <% end %>

    <%= link_to 'Back to Product List', admin_products_path %>

</div>

app/views/admin/products/index.html.erb
<h1 class="jumbotron">Admin | Products</h1>

<div class="container">
  <div class="row">

    <%= link_to 'Add Product', new_admin_product_path %>

    <div class="col-12 card">

      <table class="table">
        <thead>
          <th>Name</th>
          <th>Description</th>
          <th>Price</th>
        </thead>
        <tbody>
        </tbody>
        <%= render partial: "admin_product", collection: @products %>
      </table>
      
    </div>

  </div>
</div>

app/views/admin/products/new.html.erb
<h1 class="jumbotron">Add a Product</h1>

<div class="container">

    <%= bootstrap_form_for [:admin, @product], class: "form-horizontal" do |f| %>

        <%= f.text_field :name %>
        <%= f.text_area :description %>
        <!-- <%#= f.association :categories, collection: Category.all, as: :check_boxes, include_hidden: false %> -->

        <%= f.button :submit%>
    
    <% end %>

    <%= link_to 'Back to Product List', admin_products_path %>

</div>